apiVersion: v1
kind: ResourceQuota
metadata:
  name: nephoran-production-quota
  namespace: nephoran-production
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "20"
    pods: "100"
    services: "20"
    services.loadbalancers: "5"
    services.nodeports: "0"  # No NodePorts in production
    configmaps: "50"
    secrets: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nephoran-production-limits
  namespace: nephoran-production
spec:
  limits:
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
    type: Container
  - max:
      cpu: "32"
      memory: "64Gi"
    min:
      cpu: "500m"
      memory: "512Mi"
    type: Pod
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim