apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-deployments
spec:
  template:
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
        # Prevent privilege escalation at pod level
        supplementalGroups: []
      
      # Disable service account token auto-mounting where not needed
      automountServiceAccountToken: false
      
      # Container-level security context (applies to all containers)
      containers:
      - name: all-containers
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        
        # Resource limits to prevent DoS
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
            ephemeral-storage: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 100Mi
        
        # Liveness and readiness probes
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3