# Dependabot configuration for Nephoran Intent Operator
# This configuration ensures dependencies are kept up-to-date and secure

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "auto-merge"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sigs.k8s.io/*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

  # RAG Python dependencies
  - package-ecosystem: "pip"
    directory: "/rag-python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    assignees:
      - "ai-team"
    commit-message:
      prefix: "python-deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "rag-api"
      - "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"

  # Terraform modules (if any)
  - package-ecosystem: "terraform"
    directory: "/deployments/multi-region/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "infrastructure-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"