# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Go modules dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "thc1006"
    assignees:
      - "thc1006"
    commit-message:
      prefix: "build(deps): "
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    # Security updates get higher priority
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    # Group non-security updates by ecosystem
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
        update-types:
          - "minor"
          - "patch"
      kubernetes-dependencies:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "thc1006"
    assignees:
      - "thc1006"
    commit-message:
      prefix: "build(docker): "
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "thc1006"
    assignees:
      - "thc1006"
    commit-message:
      prefix: "ci: "
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated"

  # Helm dependencies
  - package-ecosystem: "bundler"
    directory: "/deployments/helm"
    schedule:
      interval: "monthly"
      day: 15
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "thc1006"
    assignees:
      - "thc1006"
    commit-message:
      prefix: "build(helm): "
    labels:
      - "dependencies"
      - "helm"
      - "automated"

  # Python dependencies (for rag-python module)
  - package-ecosystem: "pip"
    directory: "/rag-python"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "thc1006"
    assignees:
      - "thc1006"
    commit-message:
      prefix: "build(python): "
    labels:
      - "dependencies"
      - "python"
      - "rag"
      - "automated"

# Global settings for all ecosystems
enable-beta-ecosystems: true