# Security Policy as Code for Nephoran Intent Operator
# This policy enforces comprehensive security controls for telecommunications workloads
# Compliant with O-RAN WG11 Security Specifications

apiVersion: v1
kind: SecurityPolicy
metadata:
  name: nephoran-security-policy
  version: "1.0.0"
  compliance:
    - SOC2-Type2
    - ISO27001:2022
    - PCI-DSS-v4
    - GDPR
    - O-RAN-WG11
    - 3GPP-TS-33.501

# Vulnerability Management Policy
vulnerability_management:
  scanning:
    enabled: true
    frequency: daily
    tools:
      - trivy
      - grype
      - snyk
    
  thresholds:
    critical:
      action: block
      sla_hours: 4
      auto_remediate: true
    high:
      action: alert
      sla_hours: 24
      require_approval: true
    medium:
      action: warn
      sla_hours: 72
      track: true
    low:
      action: log
      sla_hours: 168
      review_quarterly: true
  
  cve_management:
    auto_patch: true
    test_before_apply: true
    rollback_on_failure: true
    exclusions:
      require_justification: true
      max_duration_days: 30
      require_compensating_controls: true

# Container Security Requirements
container_security:
  runtime:
    user: non-root
    uid_min: 10000
    read_only_root_filesystem: true
    allow_privilege_escalation: false
    run_as_non_root: true
    
  capabilities:
    drop:
      - ALL
    add: []  # No additional capabilities allowed
    
  seccomp:
    profile: RuntimeDefault
    custom_profiles_allowed: false
    
  apparmor:
    enabled: true
    profile: runtime/default
    
  selinux:
    enabled: true
    level: "s0:c123,c456"
    
  resource_limits:
    cpu:
      min: "100m"
      max: "2000m"
    memory:
      min: "128Mi"
      max: "4Gi"
    ephemeral_storage:
      max: "2Gi"
      
  image_security:
    registry_whitelist:
      - "registry.nephoran.io"
      - "ghcr.io/nephoran"
    require_signature: true
    scan_on_push: true
    block_on_vulnerability: true
    distroless_only: true
    max_age_days: 30

# Network Security Policies
network_security:
  tls:
    minimum_version: "1.3"
    cipher_suites:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_AES_128_GCM_SHA256
    certificate_requirements:
      key_size_min: 4096
      signature_algorithm: SHA256WithRSA
      validity_max_days: 90
      require_san: true
      require_ca_validation: true
      
  mtls:
    enabled: true
    client_cert_required: true
    verify_depth: 3
    revocation_check: true
    
  network_policies:
    default_deny_all: true
    egress_restrictions:
      allowed_domains:
        - "*.nephio.org"
        - "*.o-ran.org"
        - "kubernetes.default.svc.cluster.local"
      blocked_ports:
        - 23  # Telnet
        - 21  # FTP
        - 80  # HTTP
        - 3389 # RDP
        
  service_mesh:
    enabled: true
    provider: istio
    strict_mtls: true
    authorization_policies: true
    
  api_gateway:
    rate_limiting:
      requests_per_second: 100
      burst: 200
    authentication:
      - oauth2
      - mtls
      - api_key
    waf_enabled: true
    ddos_protection: true

# Secrets Management
secrets_management:
  encryption:
    algorithm: AES-256-GCM
    key_derivation: PBKDF2
    iterations: 100000
    
  rotation:
    enabled: true
    frequency_days: 90
    grace_period_days: 7
    automatic: true
    
  storage:
    backend: hashicorp-vault
    seal_type: auto-unseal
    high_availability: true
    
  access_control:
    require_mfa: true
    audit_logging: true
    least_privilege: true
    
  compliance:
    no_plaintext_secrets: true
    no_hardcoded_credentials: true
    require_encryption_at_rest: true
    require_encryption_in_transit: true

# O-RAN Specific Security
oran_security:
  interfaces:
    a1:
      authentication: mutual_tls
      authorization: rbac
      encryption: required
      integrity_protection: sha256
    o1:
      netconf_ssh: true
      tls_version: "1.3"
      certificate_validation: strict
    o2:
      oauth2_required: true
      api_versioning: true
      rate_limiting: true
    e2:
      sctp_auth: true
      ipsec: true
      integrity_check: true
      
  ric_security:
    xapp_sandboxing: true
    resource_isolation: true
    code_signing: required
    runtime_protection: true
    
  ran_security:
    cu_du_ipsec: true
    fronthaul_encryption: true
    user_plane_integrity: true
    
# Compliance and Audit
compliance:
  standards:
    soc2:
      controls:
        - CC6.1  # Logical Access Controls
        - CC6.2  # Prior to Issuing System Credentials
        - CC6.3  # Removes Access
        - CC7.1  # System Monitoring
        - CC7.2  # Security Incidents
      audit_frequency: quarterly
      
    iso27001:
      controls:
        - A.9    # Access Control
        - A.12   # Operations Security
        - A.13   # Communications Security
        - A.14   # System Security
        - A.16   # Incident Management
      certification_required: true
      
    pci_dss:
      version: "4.0"
      scope: cardholder_data_environment
      quarterly_scans: true
      annual_assessment: true
      
    gdpr:
      data_classification: true
      privacy_by_design: true
      right_to_erasure: true
      data_portability: true
      
  audit:
    logging:
      retention_days: 2555  # 7 years
      encryption: true
      tamper_proof: true
      centralized: true
      
    events:
      authentication: all
      authorization: all
      data_access: all
      configuration_changes: all
      security_events: all
      
    analysis:
      real_time_correlation: true
      anomaly_detection: true
      threat_intelligence: true

# Incident Response
incident_response:
  detection:
    siem_integration: true
    ids_ips: true
    file_integrity_monitoring: true
    
  response:
    automated_containment: true
    playbook_execution: true
    forensics_collection: true
    
  recovery:
    backup_verification: daily
    disaster_recovery_test: monthly
    rto_minutes: 15
    rpo_minutes: 5
    
# Security Testing Requirements
security_testing:
  sast:
    enabled: true
    tools:
      - sonarqube
      - checkmarx
      - fortify
    quality_gate: blocking
    
  dast:
    enabled: true
    tools:
      - owasp-zap
      - burp-suite
    frequency: weekly
    
  dependency_scanning:
    enabled: true
    tools:
      - snyk
      - dependabot
      - nancy
    auto_update: true
    
  penetration_testing:
    frequency: quarterly
    provider: third_party
    scope: full_stack
    
  chaos_engineering:
    enabled: true
    experiments:
      - pod_failure
      - network_latency
      - zone_failure
    frequency: monthly

# Data Protection
data_protection:
  classification:
    levels:
      - public
      - internal
      - confidential
      - restricted
    mandatory_tagging: true
    
  encryption:
    at_rest:
      algorithm: AES-256-GCM
      key_management: hsm
    in_transit:
      tls_required: true
      vpn_for_management: true
      
  dlp:
    enabled: true
    patterns:
      - credit_card
      - ssn
      - api_keys
      - private_keys
    actions:
      - block
      - alert
      - quarantine
      
  backup:
    frequency: daily
    encryption: true
    offsite_storage: true
    immutable: true
    test_restore: weekly

# Zero Trust Architecture
zero_trust:
  principles:
    never_trust_always_verify: true
    least_privilege_access: true
    assume_breach: true
    
  implementation:
    micro_segmentation: true
    identity_based_access: true
    continuous_verification: true
    encrypted_communications: true
    
  components:
    policy_engine: true
    policy_enforcement_points: true
    identity_provider: true
    device_trust: true
    
# Security Metrics and KPIs
metrics:
  kpis:
    - mean_time_to_detect: 5  # minutes
    - mean_time_to_respond: 15  # minutes
    - vulnerability_remediation_sla: 95  # percent
    - security_training_completion: 100  # percent
    - phishing_simulation_failure: 5  # percent max
    
  reporting:
    frequency: monthly
    dashboards:
      - executive
      - operational
      - technical
    stakeholders:
      - ciso
      - security_team
      - compliance_team
      - engineering_leads