# SOPS configuration for Nephoran Intent Operator
# This file configures how SOPS encrypts secrets in the repository

creation_rules:
  # Production secrets - most restrictive
  - path_regex: "deployments/secrets/production/.*\\.yaml$"
    encrypted_regex: "^(data|stringData)$"
    age: |
      age1production_public_key_here
    pgp: >-
      PRODUCTION_PGP_FINGERPRINT_HERE
    gcp_kms: projects/nephoran-prod/locations/global/keyRings/sops/cryptoKeys/production
    azure_keyvault: https://nephoran-prod-kv.vault.azure.net/keys/sops-key/production

  # Staging secrets
  - path_regex: "deployments/secrets/staging/.*\\.yaml$"
    encrypted_regex: "^(data|stringData)$"
    age: |
      age1staging_public_key_here
    pgp: >-
      STAGING_PGP_FINGERPRINT_HERE
    gcp_kms: projects/nephoran-staging/locations/global/keyRings/sops/cryptoKeys/staging

  # Development secrets - least restrictive
  - path_regex: "deployments/secrets/dev/.*\\.yaml$"
    encrypted_regex: "^(data|stringData)$"
    age: |
      age1dev_public_key_here
    pgp: >-
      DEV_PGP_FINGERPRINT_HERE

  # Default rule for any other secrets
  - path_regex: ".*secret.*\\.yaml$"
    encrypted_regex: "^(data|stringData)$"
    age: |
      age1default_public_key_here

# Audit settings
audit:
  # Log all encryption/decryption operations
  enabled: true
  log_file: /var/log/sops-audit.log

# Key rotation settings
key_rotation:
  # Automatically rotate keys after 90 days
  max_age_days: 90
  # Alert before expiration
  alert_days_before: 7