apiVersion: v1
kind: Pod
metadata:
  name: docker-loader
spec:
  containers:
  - name: docker-loader
    image: docker:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: host-tmp
      mountPath: /host-tmp
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: host-tmp
    hostPath:
      path: /tmp
