---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-processor
  namespace: default
  labels:
    app: llm-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-processor
  template:
    metadata:
      labels:
        app: llm-processor
    spec:
      containers:
      - name: llm-processor
        image: llm-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: llm-processor
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: llm-processor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
