apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-processor
  namespace: default
  labels:
    app: llm-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-processor
  template:
    metadata:
      labels:
        app: llm-processor
    spec:
      containers:
      - name: llm-processor
        image: us-central1-docker.pkg.dev/poised-elf-466913-q2/nephoran/llm-processor:f87350a-dirty
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LLM_BACKEND_TYPE
          value: "rag"
        - name: RAG_API_URL
          value: "http://localhost:5001"
        - name: LOG_LEVEL
          value: "info"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llm-processor
  namespace: default
spec:
  selector:
    app: llm-processor
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nephio-bridge
  namespace: default
  labels:
    app: nephio-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nephio-bridge
  template:
    metadata:
      labels:
        app: nephio-bridge
    spec:
      serviceAccountName: nephio-bridge
      containers:
      - name: nephio-bridge
        image: us-central1-docker.pkg.dev/poised-elf-466913-q2/nephoran/nephio-bridge:f87350a-dirty
        imagePullPolicy: Never
        env:
        - name: LLM_PROCESSOR_URL
          value: "http://llm-processor:8080"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: probe
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephio-bridge
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nephio-bridge
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["nephoran.com"]
  resources: ["networkintents", "e2nodesets", "managedelements"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["nephoran.com"]
  resources: ["networkintents/status", "e2nodesets/status", "managedelements/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nephio-bridge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nephio-bridge
subjects:
- kind: ServiceAccount
  name: nephio-bridge
  namespace: default