# deployments/kustomize/overlays/remote/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

# For remote deployments, images are pulled from a central registry.
# The 'IfNotPresent' or 'Always' policy ensures the cluster fetches the correct version.
# The image names will be updated by the deploy.sh script.
images:
- name: llm-processor
  newName: us-central1-docker.pkg.dev/your-gcp-project/nephoran/llm-processor
- name: nephio-bridge
  newName: us-central1-docker.pkg.dev/your-gcp-project/nephoran/nephio-bridge
- name: oran-adaptor
  newName: us-central1-docker.pkg.dev/your-gcp-project/nephoran/oran-adaptor
- name: rag-api
  newName: us-central1-docker.pkg.dev/your-gcp-project/nephoran/rag-api

# This patch ensures the default service account uses the image pull secret.
patches:
- patch: |-
    - op: add
      path: /imagePullSecrets
      value:
      - name: nephoran-regcred
  target:
    kind: ServiceAccount
    name: default
