apiVersion: v1
kind: Pod
metadata:
  name: image-loader
spec:
  containers:
  - name: image-loader
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: host-tmp
      mountPath: /host-tmp
  volumes:
  - name: host-tmp
    hostPath:
      path: /tmp
