name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
      - CONTRIBUTE.md
      - CODE_OF_CONDUCT.md
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/workflow-tests.yaml
    secrets: inherit
