apiVersion: v1
kind: Service
metadata:
  name: network-intent-controller-metrics
  labels:
    app: network-intent-controller
    component: controller
    app.kubernetes.io/name: network-intent-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: nephoran-intent-operator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: network-intent-controller
  ports:
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: health
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP