apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nephoran-system

resources:
  # Prometheus deployment and configuration
  - prometheus-deployment.yaml
  - prometheus-config.yaml
  
  # Grafana deployment and dashboards
  - grafana-deployment.yaml
  - grafana-dashboards.yaml
  - grafana-dashboard-sli.yaml
  
  # ServiceMonitor for scraping metrics
  - servicemonitor.yaml

configMapGenerator:
  - name: prometheus-config
    behavior: replace
    files:
      - prometheus.yml=prometheus-config.yaml

commonLabels:
  app.kubernetes.io/part-of: nephoran-intent-operator
  app.kubernetes.io/component: monitoring

# Optional: Add network policies for security
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus
      namespace: nephoran-system
    spec:
      type: ClusterIP
      ports:
        - port: 9090
          targetPort: 9090
          protocol: TCP
          name: web
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: grafana
      namespace: nephoran-system
    spec:
      type: ClusterIP
      ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
          name: web