apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-processor
  template:
    metadata:
      labels:
        app: llm-processor
    spec:
      containers:
      - name: llm-processor
        image: thc1006/nephoran-llm-processor:latest
        command: ["/llm-processor"]
        args: ["--rag-service-url=http://rag-api:5001/process_intent"]
        ports:
        - containerPort: 8080
