apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-processor
  labels:
    app: llm-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-processor
  template:
    metadata:
      labels:
        app: llm-processor
    spec:
      containers:
      - name: llm-processor
        image: gcr.io/your-project/llm-processor:latest # This will be replaced by kustomize
        ports:
        - containerPort: 8080
        env:
        - name: RAG_API_URL
          value: "http://rag-api.default.svc.cluster.local:5001/process_intent"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi