apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oran-adaptor
  labels:
    app: oran-adaptor
    component: oran-interface
    app.kubernetes.io/name: oran-adaptor
    app.kubernetes.io/component: oran-interface
    app.kubernetes.io/part-of: nephoran-intent-operator
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: oran-adaptor
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'nephoran_oran_.*'
      action: keep
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - targetLabel: service
      replacement: oran-adaptor