# Certificate Automation Configuration for Nephoran Intent Operator
# Complete configuration for automatic certificate provisioning and rotation

# Main automation engine configuration
automation_config:
  # Provisioning settings
  provisioning_enabled: true
  auto_inject_certificates: true
  service_discovery_enabled: true
  provisioning_workers: 5
  provisioning_timeout: 300s

  # Renewal settings  
  renewal_enabled: true
  renewal_threshold: 720h  # 30 days
  renewal_workers: 3
  renewal_window: 24h
  graceful_renewal_enabled: true

  # Validation settings
  validation_enabled: true
  realtime_validation: true
  chain_validation_enabled: true
  ct_log_validation_enabled: false
  validation_cache_size: 10000
  validation_cache_ttl: 1h

  # Revocation settings
  revocation_enabled: true
  crl_check_enabled: true
  ocsp_check_enabled: true
  revocation_cache_size: 5000
  revocation_cache_ttl: 30m

  # Performance settings
  batch_size: 10
  max_concurrent_operations: 50
  operation_timeout: 120s
  retry_attempts: 3
  retry_backoff: 5s

  # Kubernetes integration
  kubernetes_integration:
    enabled: true
    namespaces:
      - "nephoran-system"
      - "default"
      - "kube-system"
      - "istio-system"
    service_selector: "app.kubernetes.io/managed-by=nephoran"
    pod_selector: "nephoran.com/inject-certificate=true"
    ingress_selector: "nephoran.com/auto-certificate=true"
    secret_prefix: "nephoran"
    annotation_prefix: "nephoran.com"

    # Admission webhook configuration
    admission_webhook:
      enabled: true
      webhook_name: "nephoran-cert-injector"
      service_name: "nephoran-cert-webhook"
      service_namespace: "nephoran-system"
      cert_dir: "/etc/webhook/certs"
      port: 9443

  # Monitoring integration
  monitoring_integration:
    prometheus_enabled: true
    jaeger_enabled: true
    grafana_enabled: true
    custom_metrics_enabled: true

  # Alerting configuration
  alerting_config:
    enabled: true
    provisioning_failure_alert: true
    renewal_failure_alert: true
    validation_failure_alert: true
    revocation_alert: true
    alert_cooldown: 15m

# Service Discovery Configuration
service_discovery:
  enabled: true
  watch_namespaces:
    - "nephoran-system"
    - "default"
    - "istio-system"
  service_annotation_prefix: "nephoran.com"
  auto_provision_enabled: true
  pre_provisioning_enabled: true

  # Template matching configuration
  template_matching:
    enabled: true
    default_template: "default"
    fallback_behavior: "default"
    
    matching_rules:
      - name: "microservice"
        priority: 100
        label_selectors:
          app.kubernetes.io/component: "microservice"
        template: "microservice"
        
      - name: "public-facing"
        priority: 200
        annotation_selectors:
          nephoran.com/public-facing: "true"
        template: "public-facing"
        
      - name: "istio-gateway"
        priority: 150
        label_selectors:
          app: "istio-gateway"
        namespace_pattern: "istio-system"
        template: "gateway"

  # Service mesh integration
  service_mesh_integration:
    enabled: true
    mesh_type: "istio"
    mtls_enabled: true
    sidecar_injection: true

# Performance Cache Configuration
performance_cache:
  l1_cache_size: 1000
  l1_cache_ttl: 5m
  l2_cache_size: 5000
  l2_cache_ttl: 30m
  pre_provisioning_enabled: true
  pre_provisioning_size: 100
  pre_provisioning_ttl: 24h
  batch_operations_enabled: true
  batch_size: 20
  batch_timeout: 30s
  metrics_enabled: true
  cleanup_interval: 1h

# Health Checker Configuration
health_checker:
  enabled: true
  default_timeout: 30s
  default_interval: 10s
  default_healthy_threshold: 3
  default_unhealthy_threshold: 3
  concurrent_checks: 10
  retry_attempts: 3
  retry_delay: 5s
  tls_verification_enabled: true
  metrics_enabled: true

# Rotation Coordinator Configuration
rotation_coordinator:
  enabled: true
  max_concurrent_rotations: 5
  default_batch_size: 2
  stabilization_delay: 30s
  health_check_timeout: 60s
  rollback_enabled: true
  rollback_timeout: 5m

# Certificate Templates
certificate_templates:
  default:
    name: "default"
    description: "Default certificate template for services"
    validity_duration: "2160h"  # 90 days
    key_type: "RSA"
    key_size: 2048
    dns_name_patterns: []
    ip_address_patterns: []
    extended_key_usages:
      - "ServerAuth"
    auto_renew: true
    renewal_threshold: "720h"  # 30 days
    metadata:
      template_type: "default"
      managed_by: "nephoran"

  microservice:
    name: "microservice"
    description: "Certificate template for microservices"
    validity_duration: "720h"  # 30 days
    key_type: "ECDSA"
    key_size: 256
    dns_name_patterns:
      - "{service}.{namespace}.svc.cluster.local"
      - "{service}.{namespace}"
    extended_key_usages:
      - "ServerAuth"
      - "ClientAuth"
    auto_renew: true
    renewal_threshold: "168h"  # 7 days
    metadata:
      template_type: "microservice"
      managed_by: "nephoran"

  public-facing:
    name: "public-facing"
    description: "Certificate template for public-facing services"
    validity_duration: "8760h"  # 1 year
    key_type: "RSA"
    key_size: 4096
    dns_name_patterns:
      - "*.{namespace}.example.com"
      - "{service}.example.com"
    extended_key_usages:
      - "ServerAuth"
    auto_renew: true
    renewal_threshold: "1440h"  # 60 days
    metadata:
      template_type: "public-facing"
      managed_by: "nephoran"

  gateway:
    name: "gateway"
    description: "Certificate template for API gateways"
    validity_duration: "4380h"  # 6 months
    key_type: "ECDSA"
    key_size: 384
    dns_name_patterns:
      - "api.example.com"
      - "gateway.{namespace}.svc.cluster.local"
    extended_key_usages:
      - "ServerAuth"
    auto_renew: true
    renewal_threshold: "720h"  # 30 days
    metadata:
      template_type: "gateway"
      managed_by: "nephoran"

# CA Backend Configuration
ca_backends:
  # Primary CA backend
  primary:
    type: "cert-manager"
    enabled: true
    config:
      issuer_name: "nephoran-ca-issuer"
      issuer_namespace: "nephoran-system"
      cluster_issuer: false

  # Backup CA backend
  backup:
    type: "vault"
    enabled: false
    config:
      vault_url: "https://vault.internal.com:8200"
      vault_path: "pki/issue/nephoran"
      auth_method: "kubernetes"
      role: "nephoran-cert-issuer"

  # External CA backend
  external:
    type: "external"
    enabled: false
    config:
      api_endpoint: "https://ca.example.com/api/v1"
      auth_token_secret: "external-ca-token"

# Security Configuration
security:
  # mTLS configuration
  mtls:
    enabled: true
    client_cert_required: true
    verify_client_cert: true
    allowed_client_dns_names:
      - "nephoran-controller"
      - "nephoran-webhook"

  # Encryption configuration
  encryption:
    private_key_encryption: true
    encryption_algorithm: "AES-256-GCM"
    key_derivation: "PBKDF2"

  # Audit configuration
  audit:
    enabled: true
    log_all_operations: true
    include_certificate_data: false
    retention_days: 90

# Monitoring and Metrics
monitoring:
  # Prometheus metrics
  prometheus:
    enabled: true
    port: 8080
    path: "/metrics"
    namespace: "nephoran"
    
    # Custom metrics
    custom_metrics:
      - name: "certificate_provisioning_duration"
        type: "histogram"
        help: "Time taken to provision certificates"
        
      - name: "certificate_renewal_success_rate"
        type: "gauge" 
        help: "Success rate of certificate renewals"
        
      - name: "active_certificates_count"
        type: "gauge"
        help: "Number of active certificates"

  # Health checks
  health:
    enabled: true
    port: 8081
    path: "/health"
    
  # Profiling
  profiling:
    enabled: false
    port: 6060

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  
  # Structured logging fields
  fields:
    service: "nephoran-cert-automation"
    component: "automation-engine"
    
  # Log sampling
  sampling:
    enabled: true
    initial: 100
    thereafter: 100

# Development and Testing
development:
  # Enable development mode features
  dev_mode: false
  
  # Mock backends for testing
  mock_backends: false
  
  # Additional debug logging
  debug_logging: false
  
  # Skip certain validations
  skip_validation: false

# Backup and Disaster Recovery
backup:
  enabled: true
  
  # Backup schedule
  schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Backup retention
  retention_days: 30
  
  # Backup storage
  storage:
    type: "s3"
    bucket: "nephoran-cert-backups"
    region: "us-west-2"
    
  # What to backup
  include:
    - certificates
    - private_keys
    - ca_certificates
    - configuration
    - audit_logs

# Disaster recovery
disaster_recovery:
  enabled: true
  
  # Recovery procedures
  procedures:
    - name: "certificate_restore"
      enabled: true
      priority: 1
      timeout: "30m"
      
    - name: "ca_restore"
      enabled: true
      priority: 2
      timeout: "15m"

# Compliance and Governance
compliance:
  # Regulatory compliance
  regulations:
    - "SOC2"
    - "ISO27001"
    - "GDPR"
    
  # Certificate policies
  policies:
    - name: "key_strength"
      enabled: true
      min_key_size: 2048
      allowed_algorithms: ["RSA", "ECDSA"]
      
    - name: "validity_period"
      enabled: true
      max_validity_days: 365
      
    - name: "san_validation"
      enabled: true
      require_san: true
      allowed_san_types: ["DNS", "IP"]