# Service Accounts for Nephoran Intent Operator Components
# Following least-privilege principle with separate SA per component
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-operator-controller
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "Main operator controller for NetworkIntent CRDs"
    security.nephoran.io/last-audit: "2025-01-07"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-llm-processor
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: llm-processor
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "LLM processing service for intent translation"
    security.nephoran.io/deny-escalation: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-rag-api
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: rag-api
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "RAG API for knowledge retrieval"
    security.nephoran.io/deny-escalation: "true"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-weaviate
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: weaviate
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "Vector database for semantic search"
    security.nephoran.io/deny-escalation: "true"
automountServiceAccountToken: false  # Weaviate doesn't need K8s API access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-oran-adaptor
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: oran-adaptor
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "O-RAN interface adapter for A1/O1/O2/E2"
    security.nephoran.io/last-audit: "2025-01-07"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-nephio-bridge
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: nephio-bridge
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "Nephio integration bridge for package management"
    security.nephoran.io/last-audit: "2025-01-07"
automountServiceAccountToken: true
---
# Service Account for metrics collection
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-metrics-reader
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "Read-only metrics collection"
    security.nephoran.io/deny-escalation: "true"
automountServiceAccountToken: true
---
# Service Account for audit logging
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nephoran-audit-logger
  namespace: nephoran-system
  labels:
    app.kubernetes.io/name: nephoran-operator
    app.kubernetes.io/component: audit
    app.kubernetes.io/managed-by: nephoran
    security.nephoran.io/rbac-version: "v1"
  annotations:
    security.nephoran.io/purpose: "Audit event collection and logging"
    security.nephoran.io/deny-escalation: "true"
automountServiceAccountToken: true