apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkintents.nephoran.com
spec:
  group: nephoran.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                intent:
                  type: string
                  description: "The original natural language intent from the user."
                parameters:
                  type: object
                  description: "Structured parameters translated from the intent by the LLM."
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: "Type of condition."
                      status:
                        type: string
                        description: "Status of the condition, one of True, False, Unknown."
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: "The last time this condition transitioned from one status to another."
                      reason:
                        type: string
                        description: "A unique, machine-readable reason for the condition's last transition."
                      message:
                        type: string
                        description: "A human-readable message indicating details about the last transition."
  scope: Namespaced
  names:
    plural: networkintents
    singular: networkintent
    kind: NetworkIntent
    shortNames:
    - ni