# Default values for nephoran-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []

# Feature flags
rag:
  enabled: false
  # RAG endpoint compatibility configuration
  compat:
    # When true, use legacy /process_intent endpoint; when false, use new /process endpoint
    enableLegacyProcessIntent: true

ml:
  enabled: false

git:
  tokenSecret: ""
  concurrentPushLimit: 4  # Maximum concurrent git push operations

# Note: LLM Processor configuration moved below to avoid duplication

# RAG API configuration (conditional deployment)
ragApi:
  enabled: false  # Controlled by rag.enabled
  replicaCount: 1
  
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001
  
  # Environment variables
  env:
    - name: WEAVIATE_URL
      value: "http://weaviate.weaviate.svc.cluster.local:8080"
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openai-credentials
          key: apiKey
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# RBAC
rbac:
  create: true

# Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: nephoran-operator.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s

# Security Configuration
security:
  # Enable mTLS for service-to-service communication
  mtls:
    enabled: false
  
  # Pod Security Standards
  podSecurityStandards:
    enforce: "restricted"
    audit: "restricted"
    warn: "restricted"
  
  # Network Policies
  networkPolicies:
    enabled: true
    allowNamespaces: []
  
  # Security scanning
  scanning:
    enabled: true
    trivy:
      enabled: true
    falco:
      enabled: false

# Secrets Configuration (SOPS-encrypted)
secrets:
  # API Keys secret
  apiKeys:
    name: "nephoran-api-keys"
    namespace: "nephoran-system"
  
  # Database credentials secret
  database:
    name: "nephoran-database-credentials"
    namespace: "nephoran-system"
  
  # Authentication secrets
  auth:
    name: "nephoran-auth-secrets"
    namespace: "nephoran-system"
  
  # TLS certificates secret
  tls:
    name: "nephoran-tls-certificates"
    namespace: "nephoran-system"
  
  # mTLS certificates secret
  mtls:
    name: "nephoran-mtls-certificates"
    namespace: "nephoran-system"
  
  # O-RAN credentials secret
  oran:
    name: "nephoran-oran-credentials"
    namespace: "nephoran-system"
  
  # External secrets operator (if using)
  external:
    enabled: false
    backend: "vault"  # vault, aws-secrets-manager, azure-keyvault, gcp-secret-manager
    refreshInterval: "1h"

# LLM Processor Configuration
llmProcessor:
  enabled: true
  replicaCount: 1
  
  # Log level
  logLevel: "info"
  
  # Metrics security configuration
  metrics:
    # When false (default), metrics are only accessible from allowed CIDR blocks
    # When true, metrics are publicly accessible (not recommended for production)
    exposePublicly: false
    # CIDR blocks allowed to access metrics when exposePublicly is false
    # Default includes common private network ranges
    allowedCIDRs:
      - "10.0.0.0/8"        # Private Class A networks
      - "172.16.0.0/12"     # Private Class B networks  
      - "192.168.0.0/16"    # Private Class C networks
      - "127.0.0.0/8"       # Localhost
  
  # LLM provider configuration
  providers:
    openai:
      enabled: true
      model: "gpt-4o-mini"
    anthropic:
      enabled: false
      model: "claude-3-sonnet"
    azure:
      enabled: false
      deployment: "gpt-4"
    google:
      enabled: false
      model: "gemini-pro"
  
  # Database configuration
  database:
    enabled: false
    type: "postgres"
  
  image:
    repository: thc1006/nephoran-llm-processor
    pullPolicy: IfNotPresent
    tag: "latest"
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  # Health check configuration
  healthCheck:
    enabled: true
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 30
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
      failureThreshold: 3
      periodSeconds: 10
      initialDelaySeconds: 5
      timeoutSeconds: 5
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Node selection
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Pod security context
  podSecurityContext:
    fsGroup: 65534
  
  # RAG service configuration (conditional)
  ragService:
    # Base URL for RAG API service (endpoint path determined by rag.compat.enableLegacyProcessIntent)
    url: "http://rag-api:5001"

# Weaviate Vector Database
weaviate:
  enabled: false
  service:
    port: 8080
    grpcPort: 50051