apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-processor
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-controller
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-controller
spec:
  replicas: 3